Django/mysite/food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(),name='index'),
    #/food/1
    # path('<int:item_id>/', views.FoodDetail.as_view(), name='detail'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),

    path('item/',views.item,name='item'),
    #additem
    # path('add',views.create_item,name='create_item'),
    path('add',views.CreateItem.as_view(),name='create_item'),

    #edititem
    path('update/<int:id>/',views.update_item,name="update_item"),

    #deleteItem
    path('delete/<int:id>/',views.delete_item,name="delete_item"),
]

Django/mysite/mysite/urls.py
from re import template
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html') , name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]




urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/mysite/users/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

Django/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

Django/mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()
    #Meta class is a class that provides information about the class itself.
    #  here the meta class holds info about the registerForm class

    class Meta:
        model=User #the form(RegisterForm) belongs to the user model 
        fields=['username','email','password1','password2']

Django/mysite/food/views.py
from multiprocessing import context
from django.shortcuts import render,redirect
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# this is a function based view. (not used here)
def index(request):
    item_list=Item.objects.all()
    context={
       'item_list':item_list,
    }
    return render(request, 'food/index.html', context )

#This is a class based view. This view is used here to display the lis of food itmes
class IndexClassView(ListView):
    model=Item;
    template_name='food/index.html'
    context_object_name='item_list'

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

# this is a function based view. (not used here)
def detail(request,item_id):
    item =Item.objects.get(pk=item_id)
    context ={
        'item':item,
    }
    return render(request, 'food/detail.html', context)
#This is a class based view. This view is used here.
class FoodDetail(DetailView):
    model=Item
    template_name='food/detail.html'

# this is a function based view. (not used here)
def create_item(request):
    form=ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form})

#This is a class based view. This view is used here.
class CreateItem(CreateView):
    model=Item;
    fields=['item_name', 'item_desc', 'item_price', 'item_image']
    template_name='food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name=self.request.user
        return super().form_valid(form)

def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form':form, 'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)
    
    if request.method=='POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html', {'item':item})

    

Django/mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.



def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')

    else:
        form=RegisterForm()
    return render(request,'users/register.html', {'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

Django/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar">
        <a class="nav-item" href="{% url 'food:create_item' %}">Add Item</a>
        <a class="nav-item" href="#">Delete Item</a>
        <a class="nav-item" href="#">View Item</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">LogOut</a>
        <a href="{% url 'profile' %}">Profile</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}

    </div>
    </nav>  
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags}}">{{ message }}</div>
            
            {% endfor %}
            {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

Django/mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img  width="400px" height ="400px" src="{{ item.item_image}}" class="card">
        </div>
        <div class="col-md-6">
            <!-- This is used for function based views which is not used here now -->
            <!-- <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>${{ item.item_price }}</h3> -->
            
            <!-- This is the used here as the class based views are made now -->
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            
        </div>
    </div>
    


</div>


{% endblock %}

Django/mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
<body>

    {% block body %}

    {% for item in item_list %}
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <img class="card" width="300px" height="300px" src="{{ item.item_image }}/">
        </div>
        <div class="col-md-4">
           <h3>{{item.item_name}}</h3> 
           <h5>{{item.item_desc}}</h5>
           <h6>{{item.item_price}}</h6>
           <h6>{{ item.user_name }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

    #below is the old code

    <ul>
        <li>
           <a href=""> {{ item.id }} ----- {{ item.item_name}}</a>
        </li>
    </ul>

   




</body>
</html>

Django/mysite/food/templates/food/item-delete.html
<form method="POST">
{% csrf_token %}
<h2>Sir you sure you want to delete {{ item.item_name }}</h2>
<button type="submit">Confirm</button>
</form>

Django/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}


<div class="container" >
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-hearder text-white bg-info" >
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button type="submit">Save</button>
                    </form>    
                     </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}